### ISSUE TITLE
Data da palestra

### ISSUE THREAD

**Issue by gfkauer** [free-time/free-time.github.io#132]
Sugiro incluir a data da palestra nas informações.
Incluir também a opção de ordenar por esta data.

**Comment by walternascimentobarroso** [comment]
Acredito que ficaria bem legal, evitando de assistir palestras muito desatualizadas e ajudando na organização tambem.

:+1:

**Comment by andersoonweb** [comment]
Opa @gfkauer, boa ideia. Já vinha tendo ela há algum tempo, porém não implementei ainda. 

@walternascimentobarroso , sua posição é **MUITO** legal, porém tem um contra. Por exemplo, tem palestras antigas que são muito boa, como essa [aqui.](https://www.youtube.com/watch?v=m1iV2C44Duc) Se você vê o ano de cara, nem vai querer ver, no entanto é essencial para uma pessoa que está começando. Aquela pessoa que faz isso:

``` css
.nav-bar {
 background: #06c;
}
.nav-bar ul{
 margin: 0;
 padding: 0;
}
.nav-bar ul li {
 display: inline-block;
}
.nav-bar ul li a {
 color: #FFF;
}
```

Ao termino dá palestra, ela vai passar a ter outra visão.

Mas irei implementar @gfkauer e @walternascimentobarroso ! Muito obrigado por estar contribuindo com o projeto. Se vocês poderem ajudar, seria ótimo! :+1:
